# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/blackberry/venice/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/blackberry/venice

# ADSP
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/adsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/adsprpcd \
    vendor/blackberry/venice/proprietary/vendor/lib64/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadsprpc.so

# Audio
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdb-fts.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbloader.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbrtac.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadiertac.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudcal.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdb-fts.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbloader.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbrtac.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadiertac.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudcal.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaptXHD_encoder.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaptX_encoder.so

# Audio FX
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib/soundfx/libqcbassboost.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcbassboost.so \
    vendor/blackberry/venice/proprietary/vendor/lib/soundfx/libqcreverb.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcreverb.so \
    vendor/blackberry/venice/proprietary/vendor/lib/soundfx/libqcvirt.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcvirt.so \
    vendor/blackberry/venice/proprietary/vendor/lib/soundfx/libmmieffectswrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libmmieffectswrapper.so

# Camera
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/fastrpc_shell_0:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/fastrpc_shell_0 \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libadsp_fd_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libadsp_fd_skel.so \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libapps_mem_heap.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libapps_mem_heap.so \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libdspCV_skel.so \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libfastcvadsp_skel.so \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libfastcvadsp.so \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libobjectMattingApp_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libobjectMattingApp_skel.so \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libpanorama_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libpanorama_skel.so \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libscveBlobDescriptor_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libscveBlobDescriptor_skel.so \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libscveObjectSegmentation_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libscveObjectSegmentation_skel.so \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libscveORC_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libscveORC_skel.so \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libscveT2T_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libscveT2T_skel.so \
    vendor/blackberry/venice/proprietary/vendor/lib/rfsa/adsp/libscveTextReco_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libscveTextReco_skel.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadsprpc.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libfastcvadsp_stub.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfastcvadsp_stub.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libfastcvopt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfastcvopt.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libflash_pmic.so:$(TARGET_COPY_OUT_VENDOR)/lib/libflash_pmic.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libjpegdhw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdhw.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libjpegdmahw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdmahw.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libjpegehw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegehw.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_frame_algorithm.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_is.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_is.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_pp_buf_mgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pp_buf_mgr.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_q3a_core_qc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_q3a_core.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_q3a_release.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_q3a_release.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_sensor_debug.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_debug.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_algorithm.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_vis_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vis_module.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vpe_module.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_wnr_module.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_a2030.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_a2030.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_cac2_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_cac2_lib.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_eeprom_util.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_eeprom_util.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_eztune_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_eztune_module.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_faceproc.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_gb_lib.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_imglib_faceproc_adspstub.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib_faceproc_adspstub.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_imx230.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx230.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libSonyIMX230PdafLibrary.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSonyIMX230PdafLibrary.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_abf44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_abf44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_bcc44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bcc44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_be_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_be_stats44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_bf_scale_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bf_scale_stats44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_bf_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bf_stats44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_bg_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bg_stats44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_bhist_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bhist_stats44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_bpc44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bpc44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_chroma_enhan40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_chroma_enhan40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_chroma_suppress40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_chroma_suppress40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_clamp_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_encoder40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_clamp_video40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_video40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_viewfinder40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_clf44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clf44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_color_correct40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_correct40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_color_xform_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_xform_encoder40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_xform_viewfinder40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_cs_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_cs_stats44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_demosaic44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_demosaic44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_demux40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_demux40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_fovcrop_encoder40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_fovcrop_viewfinder40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_gamma44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_gamma44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_ihist_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_ihist_stats44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_linearization40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_linearization40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_ltm44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_ltm44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_luma_adaptation40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_luma_adaptation40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_mce40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_mce40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_mesh_rolloff44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_mesh_rolloff44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_rs_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_rs_stats44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_scaler_encoder44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_scaler_encoder44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_scaler_viewfinder44.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_sce40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_sce40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_sub_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_sub_module.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_isp_wb40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_wb40.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_pdaf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdaf.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_pdafcamif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdafcamif.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_ppbase_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ppbase_module.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_algo.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_vpu_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_vpu_module.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmipl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmipl.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmqjpegdma.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpegdma.so \
    vendor/blackberry/venice/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libois_rumbaS4.so:$(TARGET_COPY_OUT_VENDOR)/lib/libois_rumbaS4.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqomx_jpegdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegdec.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqomx_jpegenc_pipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc_pipe.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libSonyIMX230PdafLibrary.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSonyIMX230PdafLibrary.so

# Camera extra libs
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromaflash.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromaflash.so \
    vendor/blackberry/venice/proprietary/vendor/lib/liboptizoom.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboptizoom.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libseemore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libseemore.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libtrueportrait.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtrueportrait.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libubifocus.so:$(TARGET_COPY_OUT_VENDOR)/lib/libubifocus.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCB.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libCB.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_trueportrait_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_trueportrait_lib.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_stillmore_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_stillmore_lib.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_ubifocus_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ubifocus_lib.so

# Camera actuator
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib/libactuator_ak7371.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_ak7371.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libactuator_ak7371_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_ak7371_camcorder.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libactuator_ak7371_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_ak7371_camera.so

# Camera chromatix
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_common.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_cpp_liveshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_cpp_preview.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_cpp_snapshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_cpp_video.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_default_video.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_lgit_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_lgit_common.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_lgit_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_lgit_cpp_liveshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_lgit_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_lgit_cpp_preview.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_lgit_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_lgit_cpp_snapshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_lgit_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_lgit_cpp_video.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_lgit_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_lgit_default_video.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_lgit_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_lgit_liveshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_lgit_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_lgit_postproc.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_lgit_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_lgit_preview.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_lgit_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_lgit_snapshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_lgit_video_24fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_lgit_video_24fps.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_liveshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_postproc.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_preview.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_semco_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_semco_common.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_semco_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_semco_cpp_liveshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_semco_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_semco_cpp_preview.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_semco_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_semco_cpp_snapshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_semco_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_semco_cpp_video.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_semco_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_semco_default_video.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_semco_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_semco_liveshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_semco_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_semco_postproc.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_semco_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_semco_preview.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_semco_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_semco_snapshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_semco_video_24fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_semco_video_24fps.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_snapshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_a2030_video_24fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_a2030_video_24fps.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_common.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_cpp_hfr_120.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_cpp_hfr_60.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_cpp_hfr_90.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_cpp_liveshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_cpp_preview.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_cpp_snapshot_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_cpp_snapshot_hdr.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_cpp_snapshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_cpp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_cpp_video_4k.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_cpp_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_cpp_video_hdr.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_cpp_video.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_default_video.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_hfr_120.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_hfr_60.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_hfr_90.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_liveshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_postproc.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_preview.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_snapshot_flash.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_snapshot_flash.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_snapshot_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_snapshot_hdr.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_snapshot.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_video_24fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_video_24fps.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_video_4k.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libchromatix_imx230_bbry_video_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx230_bbry_video_hdr.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libllvd_smore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvd_smore.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_chromaflash_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_chromaflash_lib.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_llvd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_llvd.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_optizoom_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_optizoom_lib.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_pdaf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdaf.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_pdafcamif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdafcamif.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_ppbase_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ppbase_module.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_algo.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_vpu_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_vpu_module.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tuning.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_tuning_lookup.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tuning_lookup.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera2_mct.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_mct.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmm-qcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-qcamera.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_dbg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dbg.so \

# Camera eeprom
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_bbrya2030_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_bbrya2030_eeprom.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libmmcamera_bbrya2030_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera_bbrya2030_eeprom.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libmmcamera_bbryimx230_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_bbryimx230_eeprom.so

# Camera firmware
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/blackberry/venice/proprietary/vendor/firmware/RumbaS4_SEMCO_10339.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/camera/RumbaS4_SEMCO_10339.bin \
    vendor/blackberry/venice/proprietary/vendor/firmware/RumbaS4OisFirmware.info:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/camera/RumbaS4OisFirmware.info \
# CNE
PRODUCT_PACKAGES += \
    CNEService

# IMS
PRODUCT_PACKAGES += \
    RCSBootstraputil \
    RcsImsBootstraputil \
    rcsimssettings \
    rcsservice \
    ims_venice \

# IMS
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/ims_rtp_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/ims_rtp_daemon \
    vendor/blackberry/venice/proprietary/vendor/bin/imsdatadaemon:$(TARGET_COPY_OUT_VENDOR)/bin/imsdatadaemon \
    vendor/blackberry/venice/proprietary/vendor/bin/imsqmidaemon:$(TARGET_COPY_OUT_VENDOR)/bin/imsqmidaemon \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-ims-rcscmjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-ims-rcscmjni.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-imsSDP.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsSDP.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-imsdpl.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsdpl.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-imsqimf.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsqimf.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-imsrcs.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcs.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-imsrcscm.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcscm.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-imsrcscmclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcscmclient.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-imsrcscmservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcscmservice.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-imss.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imss.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-imsvt.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsvt.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-imsxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsxml.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-rcsimssjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rcsimssjni.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-rcsjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rcsjni.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libimscamera_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimscamera_jni.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-ims-rcscmjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-ims-rcscmjni.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-imsSDP.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsSDP.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-imsdpl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsdpl.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-imsqimf.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsqimf.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-imsrcs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcs.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-imsrcscm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcscm.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-imsrcscmclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcscmclient.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-imsrcscmservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcscmservice.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-imss.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imss.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-imsvt.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsvt.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-imsxml.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsxml.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-rcsimssjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rcsimssjni.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-rcsjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rcsjni.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libimscamera_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimscamera_jni.so

PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/cnd:$(TARGET_COPY_OUT_VENDOR)/bin/cnd \
    vendor/blackberry/venice/proprietary/vendor/lib64/com.quicinc.cne.api@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.api@1.0.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/com.quicinc.cne.constants@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.constants@1.0.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/com.quicinc.cne.constants@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.constants@2.0.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/com.quicinc.cne.server@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.quicinc.cne.server@2.0.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libcne.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcne.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcneapiclient.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libcneoplookup.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcneoplookup.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libcneqmiutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcneqmiutils.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libcneconn.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcneconn.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libcne.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcne.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneapiclient.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libcneqmiutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneqmiutils.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libcneconn.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneconn.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libwms.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwms.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libwqe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwqe.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/vendor.qti.hardware.data.latency@1.0_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.data.latency@1.0_vendor.so

# DPM
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/dpmQmiMgr:$(TARGET_COPY_OUT_VENDOR)/bin/dpmQmiMgr \
    vendor/blackberry/venice/proprietary/vendor/lib64/com.qualcomm.qti.dpm.api@1.0_vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.qualcomm.qti.dpm.api@1.0_vendor.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libdpmqmihal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdpmqmihal.so \

# DRM
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/qseecomd:$(TARGET_COPY_OUT_VENDOR)/bin/qseecomd \
    vendor/blackberry/venice/proprietary/vendor/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libQSEEComAPI.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libQSEEComAPI.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmfs.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmtime.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librpmb.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libssd.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libmdtp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdtp.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libsecureui.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecureui.so \
    vendor/blackberry/venice/proprietary/vendor/lib/lib-sec-disp.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-sec-disp.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libsecureui_svcsock.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecureui_svcsock.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libSecureUILib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSecureUILib.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libsecureuisvc_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsecureuisvc_jni.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libStDrvInt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libStDrvInt.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libsecureui.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsecureui.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libsecureui_svcsock.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsecureui_svcsock.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libSecureUILib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libSecureUILib.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libsecureuisvc_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsecureuisvc_jni.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libStDrvInt.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libStDrvInt.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/lib-sec-disp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-sec-disp.so \
    
# Widevine
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/hw/android.hardware.drm@1.0-service.widevine:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm@1.0-service.widevine \
    vendor/blackberry/venice/proprietary/vendor/etc/init/android.hardware.drm@1.0-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.0-service.widevine.rc \
    vendor/blackberry/venice/proprietary/vendor/firmware/widevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b00 \
    vendor/blackberry/venice/proprietary/vendor/firmware/widevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b01 \
    vendor/blackberry/venice/proprietary/vendor/firmware/widevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b02 \
    vendor/blackberry/venice/proprietary/vendor/firmware/widevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b03 \
    vendor/blackberry/venice/proprietary/vendor/firmware/widevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mdt \
    vendor/blackberry/venice/proprietary/vendor/lib64/libwvhidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwvhidl.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libwvhidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvhidl.so
        
# Gatekeeper
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib64/hw/gatekeeper.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.msm8992.so \
    vendor/blackberry/venice/proprietary/vendor/lib/hw/gatekeeper.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.msm8992.so

# GPS
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib64/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgeofence.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libizat_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libizat_core.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/liblbs_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblbs_core.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libflp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libflp.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/hw/flp.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/flp.default.so \
    vendor/blackberry/venice/proprietary/vendor/lib/hw/flp.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/flp.default.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libloc_api_v02.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libloc_api_v02.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libloc_ds_api.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libloc_ds_api.so

# GPU
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib/hw/vulkan.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vulkan.msm8992.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriver_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/hw/vulkan.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vulkan.msm8992.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libRSDriver_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno_sha1.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno_sha1.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOpenCL.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-qcom.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qcom.so \

# Graphics
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglSubDriverAndroid.so \
    vendor/blackberry/venice/proprietary/vendor/lib/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_esx.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libC2D2.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadreno_utils.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libc2d30-a4xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a4xx.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgsl.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-glnext.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/eglSubDriverAndroid.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libEGL_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv1_CM_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv2_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_adreno.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_esx.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libC2D2.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadreno_utils.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libc2d30-a4xx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libc2d30-a4xx.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgsl.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-glnext.so

# Graphics firmware
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw \
    vendor/blackberry/venice/proprietary/vendor/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw \

# Tomtom firmware
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b02 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b04 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b05 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b06 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b08 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b10 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b11 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b12 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b14 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b16 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b18 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b20 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.b21:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b21 \
    vendor/blackberry/venice/proprietary/vendor/firmware/cpe.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.mdt \

# Keystore
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib64/libkmcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkmcrypto.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libkmcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkmcrypto.so
#    vendor/blackberry/venice/proprietary/vendor/lib64/hw/keystore.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.msm8992.so \
#    vendor/blackberry/venice/proprietary/vendor/lib/hw/keystore.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.msm8992.so \

# Media
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib/libOmxAacDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxAacDec.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libOmxEvrcDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxEvrcDec.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libOmxQcelp13Dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxQcelp13Dec.so

# Perf
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/energy-awareness:$(TARGET_COPY_OUT_VENDOR)/bin/energy-awareness \
    vendor/blackberry/venice/proprietary/vendor/bin/msm_irqbalance:$(TARGET_COPY_OUT_VENDOR)/bin/msm_irqbalance \
    vendor/blackberry/venice/proprietary/vendor/bin/perfd:$(TARGET_COPY_OUT_VENDOR)/bin/perfd \
    vendor/blackberry/venice/proprietary/vendor/lib/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-perfd-client.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqti-perfd-client.so \
    vendor/blackberry/venice/proprietary/vendor/etc/perf-profile0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile0.conf \
    vendor/blackberry/venice/proprietary/vendor/etc/perf-profile1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile1.conf \
    vendor/blackberry/venice/proprietary/vendor/etc/perf-profile2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile2.conf \
    vendor/blackberry/venice/proprietary/vendor/etc/perf-profile3.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile3.conf \
    vendor/blackberry/venice/proprietary/vendor/etc/perf-profile4.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile4.conf \
    vendor/blackberry/venice/proprietary/vendor/etc/perf-profile5.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile5.conf

# Peripheral manager
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/pm-proxy:$(TARGET_COPY_OUT_VENDOR)/bin/pm-proxy \
    vendor/blackberry/venice/proprietary/vendor/bin/pm-service:$(TARGET_COPY_OUT_VENDOR)/bin/pm-service \
    vendor/blackberry/venice/proprietary/vendor/lib64/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libperipheral_client.so

# Postprocessing
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/mm-pp-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-pp-daemon \
    vendor/blackberry/venice/proprietary/vendor/lib/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor1.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libdisp-aba.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdisp-aba.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libmm-abl-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-abl-oem.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libmm-abl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-abl.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libmm-als.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-als.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libmm-disp-apis.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-disp-apis.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libmm-qdcm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-qdcm.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsensor1.so

# Qualcomm framework
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/irsc_util:$(TARGET_COPY_OUT_VENDOR)/bin/irsc_util \
    vendor/blackberry/venice/proprietary/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsi_netctrl.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdp.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_helper.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libsmemlog.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsmemlog.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdiag.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsi_netctrl.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsutils.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libidl.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdi.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdp.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_cci.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_helper.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_qmux.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_common_so.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_csi.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_encdec.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libsmemlog.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsmemlog.so

# Radio
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/bin/netmgrd \
    vendor/blackberry/venice/proprietary/vendor/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/bin/qmuxd \
    vendor/blackberry/venice/proprietary/vendor/bin/rfs_access:$(TARGET_COPY_OUT_VENDOR)/bin/rfs_access \
    vendor/blackberry/venice/proprietary/vendor/bin/rmt_storage:$(TARGET_COPY_OUT_VENDOR)/bin/rmt_storage \
    vendor/blackberry/venice/proprietary/vendor/bin/qti:$(TARGET_COPY_OUT_VENDOR)/bin/qti \
    vendor/blackberry/venice/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/blackberry/venice/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/blackberry/venice/proprietary/vendor/etc/data/qmi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/qmi_config.xml \
    vendor/blackberry/venice/proprietary/vendor/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdmdetect.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so \
    vendor/blackberry/venice/proprietary/vendor/lib/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblqe.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libconfigdb.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdmdetect.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnetmgr.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmiservices.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-qmi-1.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qcril-hook-oem.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libsystem_health_mon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsystem_health_mon.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxml.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libbbry_vs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbbry_vs.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libmep_transform.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmep_transform.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblqe.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libril-qc-radioconfig.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-radioconfig.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqcmaputils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqcmaputils.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libcellular_input_service.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcellular_input_service.so \
    vendor/blackberry/venice/proprietary/vendor/qcril.db:$(TARGET_COPY_OUT_VENDOR)/qcril.db

# Sensors
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib64/hw/sensors.avengers.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sensors.avengers.so \
    vendor/blackberry/venice/proprietary/vendor/firmware/sensor-hub.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sensor-hub.bin \
    vendor/blackberry/venice/proprietary/vendor/firmware/sensor_hub_mx_venice.zip:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/sensor_hub_mx_venice.zip \
    vendor/blackberry/venice/proprietary/vendor/lib/hw/activity_recognition.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/activity_recognition.msm8992.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/hw/activity_recognition.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/activity_recognition.msm8992.so \

# Signed Venus (media) firmware
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00 \
    vendor/blackberry/venice/proprietary/vendor/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01 \
    vendor/blackberry/venice/proprietary/vendor/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02 \
    vendor/blackberry/venice/proprietary/vendor/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03 \
    vendor/blackberry/venice/proprietary/vendor/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04 \
    vendor/blackberry/venice/proprietary/vendor/firmware/venus.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mbn \
    vendor/blackberry/venice/proprietary/vendor/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt

# Thermal
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/thermal-engine:$(TARGET_COPY_OUT_VENDOR)/bin/thermal-engine \
    vendor/blackberry/venice/proprietary/vendor/lib/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermalclient.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libthermalclient.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libthermalioctl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libthermalioctl.so

# Time services
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib64/libtime_genoff.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtime_genoff.so

# Keyboard
PRODUCT_PACKAGES += \
    BlackBerryKeyboard

# BB Keyboard Dependencies
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/priv-app/BlackBerryKeyboard/com.blackberry.only.jar:system/framework/com.blackberry.only.jar \
    vendor/blackberry/venice/proprietary/priv-app/BlackBerryKeyboard/com.blackberry.only.xml:system/etc/permissions/com.blackberry.only.xml

# Touch screen firmware
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/60253-001.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/60253-001.img \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/60253-002.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/60253-002.img \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/60253-003.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/60253-003.img \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/60253-101.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/60253-101.img \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/61516-001.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/61516-001.img \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/61516-002.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/61516-002.img \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/61516-003.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/61516-003.img \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/61516-004.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/61516-004.img \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/61516-005.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/61516-005.img \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/61516-006.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/61516-006.img \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/s1403/61516.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/s1403/61516.img \
    vendor/blackberry/venice/proprietary/vendor/firmware/synaptics/s3508/60253.img:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics/s3508/60253.img

# Widevine DRM
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib64/mediadrm/libwvdrmengine.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libdrmdecrypt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmdecrypt.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmfs.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmtime.so \
    vendor/blackberry/venice/proprietary/vendor/lib/libtzdrmgenprov.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtzdrmgenprov.so \
    vendor/blackberry/venice/proprietary/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmfs.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmtime.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libtzdrmgenprov.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtzdrmgenprov.so

# NVRAM
PRODUCT_COPY_FILES += \
    vendor/blackberry/venice/proprietary/vendor/bin/vtnvfsd:$(TARGET_COPY_OUT_VENDOR)/bin/vtnvfsd \
    vendor/blackberry/venice/proprietary/vendor/lib64/libsbgse.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsbgse.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libsecureservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsecureservice.so \
    vendor/blackberry/venice/proprietary/vendor/lib64/libqseecomimport.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqseecomimport.so
